#' @title Print Summary of an Empirical Calibration Density

#' @description
#' This function prints a summary of an empirical calibration density generated by \code{"clade.date"}.

#' @param x an object generated by [clade.date].
#' @param param a character string specifying the format for the report of the estimated parameters matching that of common programs for Bayesian time-tree estimation: \code{"standard"} or \code{"mrbayes"}.
#' @param digits number of significant digits to report (default to 4)

#' @details
#' Parameters of the probability density function fit, if present, are reported their standard parameterizations (\code{"standard"} see [Distributions]) or the parameterization used in MrBayes (\code{"mrbayes"}), in which the gamma and lognormal distributions are parameterized by their mean and standard deviation.

#' @return a list with the following elements:
#' \itemize{
#' \item{Quantiles}
#' \item{KStest}
#' \item{PDFfit}
#' }

#' @import stats

#' @examples
#'
#' ## Matrix of fossil ages including maximum and minimum bounds for each
#' Fages <- cbind(c(50, 38, 30, 14, 3.5), c(56, 45, 35, 14, 6))
#'
#' ## Basic execution
#'   clade.date(Fages)
#'
#' ## Alternative options
#'   X <- clade.date(Fages, method="RobertsSolow", plot=TRUE, PDFfitting="lognormal")
#'   summary(X)
#'
#' @author Santiago Claramunt, \email{s.claramunt@@utoronto.ca}

#'
#'
#' @seealso [clade.date].

#' @export

summary.clade.date <- function(x, param="standard", digits=4) {
		
	if(!is.null(x$KStest))  { print(x$KStest) }
	

	
	cat("\nQuantiles:\n")
	
	print(signif(x$Quantiles, digits= digits))
	
	if(param == "standard") {
		
		cat("\nParameters of the", x$PDFfit.model,"function:\n")
		
		print(c(offset=x$Quantiles[[1]], x$PDFfit$estimate), digits=digits)
		
	} else if(param == "mrbayes") {

			offset <- x$Quantiles[['0%']]
		
		if(x$PDFfit.model == "gamma") {			
			
			mean <- offset + x$PDFfit$estimate[["shape"]]/x$PDFfit$estimate[["rate"]]
			
			st.dev <- sqrt(x$PDFfit$estimate[["shape"]]/x$PDFfit$estimate[["rate"]]^2)
		} 
		
		if(x$PDFfit.model == "lognormal") {
						
			mean <- offset + exp( x$PDFfit$estimate[["meanlog"]] +  x$PDFfit$estimate[["sdlog"]]^2/2)
			
			st.dev <- sqrt((exp(x$PDFfit$estimate[["sdlog"]]^2)-1) * exp(2*x$PDFfit$estimate[["meanlog"]] + x$PDFfit$estimate[["sdlog"]]^2) )
		} 

		if(x$PDFfit.model == "exponential") {
						
			mean <- offset + 1/x$PDFfit$estimate[["rate"]]
			
		} 

		cat("\nParameters of the", x$PDFfit.model,"function (MrBayes format):\n")
		
		print(c(offset=offset, mean=mean, st.dev.=st.dev), digits=digits)
		
	}
}
